name: flake8 ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: x64
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Install flake8
      run: pip install flake8 flake8-nb
    - name: run flake8 ⚙️
      run: |
        find . -type f -name "*.py" | xargs flake8 --max-line-length=88 --ignore=E203,E701,W503 --exclude=./IO/Scripts/old/*
    - name: run flake8-notebook ⚙️
      if: '!cancelled()'
      run: |
        find . -type f -name "*.ipynb" -not -path "./IO/Scripts/old/*" | xargs flake8-nb --max-line-length=88 --ignore=E203,E701,W503
